app/urls.py
# -*- encoding: utf-8 -*-
"""
MIT License
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path, re_path
from app import views

urlpatterns = [
    # Matches any html file - to be used for gentella
    # Avoid using your .html in your resources.
    # Or create a separate django app.
    re_path(r'^.*\.html', views.pages, name='pages'),

    # The home page
    path('', views.index, name='home'),
    path('empresas/', views.empresas, name='empresas'),
    path('empresas/create/', views.add_empresas, name='crear_empresa'),
    path('campanas/', views.campanas_publicitarias, name='campanas_publicitarias'),
    path('campanas/create/', views.add_camapana_publicitaria, name='crear_campana'),
    path('redes/',  views.redes_sociales, name='redes_sociales'),
    path('redes/create/', views.add_red_social, name='crear_red'),
    path('ubicacion/', views.add_ubicacion,  name='crear_ubicacion'),
    path('hashtag/', views.add_hashtag, name='crear_hashtag'),
    path('acercade/', views.acerca_de, name='acerca_de'),
]

core/urls.py
# -*- encoding: utf-8 -*-
"""
MIT License
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("authentication.urls")),
    path("", include("app.urls")),
    path("", include("campanas_publicitarias.urls")) 
]

app/models.py
# -*- encoding: utf-8 -*-
"""
MIT License
Copyright (c) 2019 - present AppSeed.us
"""

from django.db import models
from django.contrib.auth.models import User , Group


# Create your models here.

class estado_empresa(models.Model):
    estado_nombre_empresa = models.CharField(blank=True, max_length=100, verbose_name='Nombre')

    class Meta():
        verbose_name = "estado_empresa"
        verbose_name_plural = "estado_empresas"

    def __str__(self):
        return self.estado_nombre_empresa

class empresa(models.Model):
    nit_empresa = models.IntegerField(null=True, unique=True, verbose_name='NIT', max_length=11)
    nombre_empresa = models.CharField(blank=True, max_length=100, verbose_name='Nombre')
    estado_empresa = models.ForeignKey(estado_empresa, on_delete=models.CASCADE, null=True)
    usuarios = models.ManyToManyField(User)

    class Meta():
        verbose_name = "empresa"
        verbose_name_plural = "empresas"

    def __str__(self):
        return self.nombre_empresa

class campana_publicitaria(models.Model):
    nombre_campana = models.CharField(blank=True, max_length=100, verbose_name='Nombre')
    descripcion_campana = models.CharField(blank=True, max_length=100, verbose_name='Descripcion')
    objetivo_campana = models.CharField(blank=True, max_length=100, verbose_name='Objetivo')
    publico_campana = models.CharField(blank=True, max_length=100, verbose_name='Publico')
    ubicacion_campana = models.CharField(blank=True, max_length=100, verbose_name='Ubicacion')
    presupuesto_campana = models.IntegerField(null=True, verbose_name='Presupuesto')
    eficacia_camapana = models.CharField(blank=True, max_length=100, verbose_name='Eficacia')
    empresa_campana = models.ForeignKey(empresa, on_delete=models.CASCADE, null=True)
    usuario_campana = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    class Meta():
        verbose_name = "campana_publicitaria"
        verbose_name_plural = "campanas_publicitarias"

    def __str__(self):
        return self.nombre_campana

    
class ubicacion(models.Model):
    nombre_ubicacion = models.CharField(blank=True, max_length=100, verbose_name='Nombre')    

    class Meta():
        verbose_name = "ubicacion"
        verbose_name_plural = "ubicaciones"

    def __str__(self):
        return self.nombre_ubicacion

class hashtag(models.Model):
    nombre_hastag = models.CharField(blank=True, max_length=100, verbose_name='Nombre')
    

    class Meta():
        verbose_name = "hashtag"
        verbose_name_plural = "hashtags"

    def __str__(self):
        return self.nombre_hastag

class red_social(models.Model):
    nombre_red_social = models.CharField(blank=True, max_length=100, verbose_name='Nombre')
    usuario_red_social = models.CharField(blank=True, max_length=100, verbose_name='Usuario')
    fecha_inicio_red_social = models.DateField(auto_now=False, auto_now_add=False,verbose_name='Fecha de Inicio')
    fecha_final_red_social = models.DateField(auto_now=False, auto_now_add=False,verbose_name='Fecha Final')
    cantidad_seguidores_red_social = models.IntegerField(null=True, verbose_name='Cantidad de seguidores')
    cantidad_likes_red_social = models.IntegerField(null=True, verbose_name='Cantidad de Likes')
    cantidad_reacciones_red_social = models.IntegerField(null=True, verbose_name='Cantidad de reacciones')
    empresa_red_social = models.ForeignKey(empresa, on_delete=models.CASCADE, null=True)
    campana_publicitaria_red_social = models.ForeignKey(campana_publicitaria, on_delete=models.CASCADE, null=True)
    ubicacion_red_social = models.ForeignKey(ubicacion, on_delete=models.CASCADE, null=True)
    hashtag_red_social = models.ForeignKey(hashtag, on_delete=models.CASCADE, null=True)

    class Meta():
        verbose_name = "red_social"
        verbose_name_plural = "redes_sociales"

    def __str__(self):
        return self.nombre_red_social

core/templates/includes/navigation.html
	<!-- [ Header ] start -->
	<header class="navbar pcoded-header navbar-expand-lg navbar-light headerpos-fixed header-blue">
		
			
        <div class="m-header">
            <a class="mobile-menu" id="mobile-collapse" href="#!"><span></span></a>
            <a href="#!" class="b-brand">
                <!-- ========   change your logo hear   ============ -->
                <img src="/static/assets/images/logo.png" alt="" class="logo">
                <img src="/static/assets/images/logo-icon.png" alt="" class="logo-thumb">
            </a>
            <a href="#!" class="mob-toggler">
                <i class="feather icon-more-vertical"></i>
            </a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a href="#!" class="pop-search"><i class="feather icon-search"></i></a>
                    <div class="search-bar">
                        <input type="text" class="form-control border-0 shadow-none" placeholder="Search here">
                        <button type="button" class="close" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                </li>
                <li class="nav-item">
                    <a href="#!" class="full-screen" onclick="javascript:toggleFullScreen()"><i class="feather icon-maximize"></i></a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li>
                    <div class="dropdown">
                        <a class="dropdown-toggle" href="#" data-toggle="dropdown"><i class="icon feather icon-bell"></i><span class="badge bg-danger"><span class="sr-only"></span></span></a>
                        <div class="dropdown-menu dropdown-menu-right notification">
                            <div class="noti-head">
                                <h6 class="d-inline-block m-b-0">Notifications</h6>
                                <div class="float-right">
                                    <a href="#!" class="m-r-10">mark as read</a>
                                    <a href="#!">clear all</a>
                                </div>
                            </div>
                            <ul class="noti-body">
                                <li class="n-title">
                                    <p class="m-b-0">NEW</p>
                                </li>
                                <li class="notification">
                                    <div class="media">
                                        <img class="img-radius" src="/static/assets/images/user/avatar-1.jpg" alt="Generic placeholder image">
                                        <div class="media-body">
                                            <p><strong>John Doe</strong><span class="n-time text-muted"><i class="icon feather icon-clock m-r-10"></i>5 min</span></p>
                                            <p>New ticket Added</p>
                                        </div>
                                    </div>
                                </li>
                                <li class="n-title">
                                    <p class="m-b-0">EARLIER</p>
                                </li>
                                <li class="notification">
                                    <div class="media">
                                        <img class="img-radius" src="/static/assets/images/user/avatar-2.jpg" alt="Generic placeholder image">
                                        <div class="media-body">
                                            <p><strong>Joseph William</strong><span class="n-time text-muted"><i class="icon feather icon-clock m-r-10"></i>10 min</span></p>
                                            <p>Prchace New Theme and make payment</p>
                                        </div>
                                    </div>
                                </li>
                                <li class="notification">
                                    <div class="media">
                                        <img class="img-radius" src="/static/assets/images/user/avatar-1.jpg" alt="Generic placeholder image">
                                        <div class="media-body">
                                            <p><strong>Sara Soudein</strong><span class="n-time text-muted"><i class="icon feather icon-clock m-r-10"></i>12 min</span></p>
                                            <p>currently login</p>
                                        </div>
                                    </div>
                                </li>
                                <li class="notification">
                                    <div class="media">
                                        <img class="img-radius" src="/static/assets/images/user/avatar-2.jpg" alt="Generic placeholder image">
                                        <div class="media-body">
                                            <p><strong>Joseph William</strong><span class="n-time text-muted"><i class="icon feather icon-clock m-r-10"></i>30 min</span></p>
                                            <p>Prchace New Theme and make payment</p>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                            <div class="noti-footer">
                                <a href="#!">show all</a>
                            </div>
                        </div>
                    </div>
                </li>
                <li>
                    <div class="dropdown drp-user">
                        <a href="#!" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="/static/assets/images/user/avatar-1.jpg" class="img-radius wid-40" alt="User-Profile-Image">
                        </a>
                        <div class="dropdown-menu dropdown-menu-right profile-notification">
                            <div class="pro-head">
                                <img src="/static/assets/images/user/avatar-1.jpg" class="img-radius" alt="User-Profile-Image">
                                <span>
                                    {{ request.user.username }}
                                </span>
                                <a href={% url 'logout' %} class="dud-logout" title="Logout">
                                    <i class="feather icon-log-out"></i>
                                </a>
                            </div>
                            <ul class="pro-body">
                                <li><a href="#" class="dropdown-item"><i class="feather icon-user"></i> Profile - {{ request.user.email }} </a></li>
                            </ul>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
        
    
    </header>
    <!-- [ Header ] end -->

core/templates/includes/scripts.html
    <script src="/static/assets/js/vendor-all.min.js"></script>
    <script src="/static/assets/js/plugins/bootstrap.min.js"></script>
    <script src="/static/assets/js/pcoded.min.js"></script>

core/templates/includes/sidebar.html
	<!-- [ navigation menu ] start -->
	<nav class="pcoded-navbar menupos-fixed menu-light ">
		<div class="navbar-wrapper  ">
			<div class="navbar-content scroll-div " >
				<ul class="nav pcoded-inner-navbar ">
					<li class="nav-item pcoded-menu-caption">
						<label>Navigation</label>
					</li>
					<li class="nav-item">
                        <a href="/ " class="nav-link ">
                            <span class="pcoded-micon">
                                <i class="feather icon-layers"></i></span><span class="pcoded-mtext">Dashboard</span></a>
					</li>
					<li class="nav-item pcoded-hasmenu">
					    <a class="nav-link ">
							<span class="pcoded-micon">
								<i class="feather icon-layout"></i></span><span class="pcoded-mtext">Empresas</span></a>
						<ul class="pcoded-submenu">
							{% if perms.app.view_empresa %}
							<li><a href="/empresas/">Consultar empresas</a></li>					        
							{% endif %}
							{% if perms.app.add_empresa %}
							<li><a href="/empresas/create/">Crear empresas</a></li>
							{% endif %}	
						</ul>
					</li>
					<li class="nav-item pcoded-hasmenu">
					    <a class="nav-link ">
							<span class="pcoded-micon">
								<i class="feather icon-layout"></i></span><span class="pcoded-mtext">Campañas</span></a>
					    <ul class="pcoded-submenu">
							{% if perms.app.view_campana_publicitaria %}
							<li><a href="/campanas/">Consultar campañas publicitarias</a></li>					        
							{% endif %}	
							{% if perms.app.add_campana_publicitaria %}
							<li><a href="/campanas/create/">Crear campaña publicitaria</a></li>					        
							{% endif %}	
					    </ul>
					</li>
					<li class="nav-item pcoded-hasmenu">
					    <a class="nav-link ">
							<span class="pcoded-micon">
								<i class="feather icon-layout"></i></span><span class="pcoded-mtext">Redes Sociales</span></a>
					    <ul class="pcoded-submenu">
							{% if perms.app.view_red_social %}
							<li><a href="/redes/">Consultar redes sociales</a></li>					        
							{% endif %}
							{% if perms.app.add_red_social %}
							<li><a href="/redes/create/">Crear redes sociales</a></li>					        
							{% endif %}
					    </ul>
					</li>
					<li class="nav-item">
                        <a href="/acercade/ " class="nav-link ">
                            <span class="pcoded-micon">
                                <i class="feather icon-layers"></i></span><span class="pcoded-mtext">Acerca de</span></a>
					</li>
				</ul>
			</div>
		</div>
	</nav>
    <!-- [ navigation menu ] end -->